name: "Check Syntax of YANG Modules"

on:
  push:
    paths:
    - '**.yang'
  pull_request:
    paths:
    - '**.yang'
  workflow_dispatch:

jobs:
  build:
    name: "Check Syntax of YANG Modules"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: "Install pyang"
      run: |
        python -m pip install --upgrade pip
        pip install pyang
   
    - name: "Lint using pyang"
      run: |
        make pyang-lint

    - name: "Adding tree files"
      run: |
        git config --global user.name 'ID Bot'
        git config --global user.email 'idbot@example.com'
        make yang-gen-tree
        ls -laR yang/
        git add 'yang/*tree.txt'
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-generate files"
        git push
